### ISSUE TITLE
Gift card

### ISSUE THREAD

**Issue by svendjanis** [Jaspero/fireshop#169]
It would be nice to have this feature, should we add it?
For example: people could buy cards with value of 10, 20, 50, 100 € and they get a code with that amount of value.

**Comment by flauc** [comment]
This is a great idea. I think we need a few things added in order to really integrate this functionality. 

- [ ] We need to have an overview of gift cards a user has
- [ ] We need to implement a way to apply gift cards to an order 
- [ ] We need to connect buying gift cards. When someone buys a gift card he needs to input an email and we then send an email with the gift card.

**Comment by flauc** [comment]
- [ ] We also need giftcard statistics page
